### ISSUE TITLE
Handle rebuilding of "block injected" PE

### ISSUE THREAD

**Issue by herrcore** [OALabs/frida-extract#2]
Fix rebuild.py to handle situations where the PE is injected as one big contiguous block.

ex.
`NtWriteVirtualMemory(0x118, 0x400000, 0x38e0020, 0x3a000, 0x3a000) -> 0x0`

**Comment by OALabs** [comment]
Fixed with new rebuild script options. 

#d2aec67aac6908c9e24deaecdbc245db519aad5b
