### ISSUE TITLE
AttributeError: 'super' object has no attribute 'disable_jit'

### ISSUE THREAD

**Issue by decker78** [OALabs/frida-extract#3]
C:\Python27\Scripts>c:\Python27\python.exe FridaExtract.py ch
Traceback (most recent call last):
  File "FridaExtract.py", line 241, in <module>
    main()
  File "FridaExtract.py", line 221, in main
    frida_driver = FridaExtract(cmd)
  File "FridaExtract.py", line 51, in __init__
    self.session.disable_jit()
  File "c:\Python27\lib\site-packages\frida\core.py", line 27
    return getattr(super(Session, self), attr)
AttributeError: 'super' object has no attribute 'disable_jit'

What could be the problem here?

**Comment by idiom** [comment]
Frida 9 defaults to the Ducktape-based JS runtime. The call has been inverted in core.py to _enable_jit_ if you don't want to use the new default.

**Comment by idiom** [comment]
@decker78 I've removed the call to disable_jit. if you get latest this will resolve the issue.
